
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/CSEProjectRoomManagementSystem?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: love1994

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true #To beautify or pretty print the SQL
          default_batch_fetch_size: 100
          #show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

server:
  port: 8050